package com.sistemamonitoreosaludpublica;

import java.awt.BorderLayout;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

public class Principal extends javax.swing.JFrame {
    DefaultTableModel defaultTableModel;
    MortalityRateDAO mortalityRateDAO;

    public Principal() {
        initComponents();
        this.setTitle("Sistema de Monitoreo de Salud Pública");
        this.setLocationRelativeTo(Principal.this);

        consultData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Datos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        panel_Graficos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        graficoBarras = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_Archivo = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenuItem();
        menu_Datos = new javax.swing.JMenu();
        menuVerDatos = new javax.swing.JMenuItem();
        menu_Graficos = new javax.swing.JMenu();
        menuVerGraficos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Tasas de Mortalidad");

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Año", "Departamento", "Sexo", "Enfermedad", "N° Defunciones", "Tasa Bruta", "Tasa Ajuste", "Error", "Lim. Inferior", "Lim. Superior", "Cluster"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDatos);

        javax.swing.GroupLayout panel_DatosLayout = new javax.swing.GroupLayout(panel_Datos);
        panel_Datos.setLayout(panel_DatosLayout);
        panel_DatosLayout.setHorizontalGroup(
            panel_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_DatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_DatosLayout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 987, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_DatosLayout.setVerticalGroup(
            panel_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_DatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        getContentPane().add(panel_Datos, "card2");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Gráfica");
        jLabel3.setAlignmentX(1.0F);
        jLabel3.setAlignmentY(1.0F);

        javax.swing.GroupLayout graficoBarrasLayout = new javax.swing.GroupLayout(graficoBarras);
        graficoBarras.setLayout(graficoBarrasLayout);
        graficoBarrasLayout.setHorizontalGroup(
            graficoBarrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        graficoBarrasLayout.setVerticalGroup(
            graficoBarrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_GraficosLayout = new javax.swing.GroupLayout(panel_Graficos);
        panel_Graficos.setLayout(panel_GraficosLayout);
        panel_GraficosLayout.setHorizontalGroup(
            panel_GraficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_GraficosLayout.createSequentialGroup()
                .addGap(486, 486, 486)
                .addComponent(jLabel3)
                .addContainerGap(492, Short.MAX_VALUE))
            .addGroup(panel_GraficosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(graficoBarras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_GraficosLayout.setVerticalGroup(
            panel_GraficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_GraficosLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(graficoBarras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(panel_Graficos, "card3");

        menu_Archivo.setText("Archivo");

        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        menu_Archivo.add(menuSalir);

        jMenuBar1.add(menu_Archivo);

        menu_Datos.setText("Datos");

        menuVerDatos.setText("Visualizar datos");
        menuVerDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVerDatosActionPerformed(evt);
            }
        });
        menu_Datos.add(menuVerDatos);

        jMenuBar1.add(menu_Datos);

        menu_Graficos.setText("Gráficos");

        menuVerGraficos.setText("Visualizar gráficos");
        menuVerGraficos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVerGraficosActionPerformed(evt);
            }
        });
        menu_Graficos.add(menuVerGraficos);

        jMenuBar1.add(menu_Graficos);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSalirActionPerformed

    private void menuVerDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVerDatosActionPerformed
        // TODO add your handling code here:
        panel_Datos.setVisible(true);
        panel_Graficos.setVisible(false);
    }//GEN-LAST:event_menuVerDatosActionPerformed

    private void menuVerGraficosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVerGraficosActionPerformed
        // TODO add your handling code here:
        panel_Datos.setVisible(false);
        panel_Graficos.setVisible(true);
        graficar();
    }//GEN-LAST:event_menuVerGraficosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    final public void consultData() {
        defaultTableModel = (DefaultTableModel) tblDatos.getModel();
        mortalityRateDAO = new MortalityRateDAO();
        
        mortalityRateDAO.all().forEach(mr -> defaultTableModel.addRow(new Object[]{
            mr.getYear(), 
            mr.getDepartment(), 
            mr.getGender(), 
            mr.getDisease(), 
            mr.getNumberDeath(), 
            mr.getGrossRate(), 
            mr.getAdjusmentRate(),
            mr.getError(),
            mr.getLowerLimit(),
            mr.getUpperLimit(),
            mr.getCluster()}));
        
        tblDatos.setModel(defaultTableModel);
    }
    
    public void graficar(){
        DefaultCategoryDataset datos = new DefaultCategoryDataset();
        
        for (MortalityRate a : mortalityRateDAO.all()) {
            if (a.getDepartment().equalsIgnoreCase("arequipa")) {
                datos.setValue(a.getNumberDeath(), a.getDisease(), a.getGender());
            }
        }
        
        JFreeChart grafico_barras = ChartFactory.createBarChart(
                "Muertes de hombres/mujeres por cada enfermedad en Peru",
                "Genero",
                "Enfermedades",
                datos,
                PlotOrientation.VERTICAL,
                true,
                true,
                false);
        ChartPanel graf = new ChartPanel(grafico_barras);
        graf.setMouseWheelEnabled(true);
        
        graficoBarras.setLayout(new BorderLayout());
        graficoBarras.add(graf,BorderLayout.NORTH);
        pack();
        repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel graficoBarras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JMenuItem menuVerDatos;
    private javax.swing.JMenuItem menuVerGraficos;
    private javax.swing.JMenu menu_Archivo;
    private javax.swing.JMenu menu_Datos;
    private javax.swing.JMenu menu_Graficos;
    private javax.swing.JPanel panel_Datos;
    private javax.swing.JPanel panel_Graficos;
    private javax.swing.JTable tblDatos;
    // End of variables declaration//GEN-END:variables
}
